# Status available at
# https://ci.appveyor.com/project/fancycode/memorymodule
version: 1.0.{build}

os:
  - Visual Studio 2015

environment:
  matrix:
    - GENERATOR: "Visual Studio 9 2008"
      UNICODE: ON
    - GENERATOR: "Visual Studio 9 2008"
      UNICODE: OFF
    - GENERATOR: "Visual Studio 10 2010"
      UNICODE: ON
    - GENERATOR: "Visual Studio 10 2010"
      UNICODE: OFF
    - GENERATOR: "Visual Studio 11 2012"
      UNICODE: ON
    - GENERATOR: "Visual Studio 11 2012"
      UNICODE: OFF
    - GENERATOR: "Visual Studio 12 2013"
      UNICODE: ON
    - GENERATOR: "Visual Studio 12 2013"
      UNICODE: OFF
    - GENERATOR: "Visual Studio 14 2015"
      UNICODE: ON
    - GENERATOR: "Visual Studio 14 2015"
      UNICODE: OFF

platform:
  - x86
  - x64

configuration:
  - Debug

install:
  - call scripts\run-appveyor.bat

build: off
test: off
deploy: off
